export const AUTH_CHANGE_EMAIL = 'AUTH_CHANGE_EMAIL';
export const AUTH_CHANGE_NICKNAME = 'AUTH_CHANGE_NICKNAME';
export const AUTH_CHANGE_PASSWORD = 'AUTH_CHANGE_PASSWORD';

export const AUTH_SET_EMAIL_ERROR = 'AUTH_SET_EMAIL_ERROR';
export const AUTH_SET_NICKNAME_ERROR = 'AUTH_SET_NICKNAME_ERROR';
export const AUTH_SET_PASSWORD_ERROR = 'AUTH_SET_PASSWORD_ERROR';
export const AUTH_CHANGED_NICKNAME_STATE = 'AUTH_CHANGED_NICKNAME_STATE';
export const AUTH_CHANGED_PASSWORD_STATE = 'AUTH_CHANGED_PASSWORD_STATE';
export const AUTH_CHANGED_EMAIL_STATE = 'AUTH_CHANGED_EMAIL_STATE';
export const AUTH_API_SUCCESS = 'AUTH_API_SUCCESS';
export const AUTH_API_ERROR = 'AUTH_API_ERROR';
export const AUTH_RESET_FORM = 'AUTH_RESET_FORM';
