version: "3.3"
services:
  user-service:
    build:
      context: ./
      dockerfile: ${PWD}/user-service/docker/development/Dockerfile
    ports:
      - "9999:8080"
    volumes:
      - ./user-service:/usr/src/app
    external_links:
      - mongo
    container_name: mafia-user-service
  game-service:
    build:
      context: ./
      dockerfile: ${PWD}/room-service/docker/development/Dockerfile
    ports:
      - "8888:8080"
    volumes:
      - ./room-service:/usr/src/app
    external_links:
      - mongo
    container_name: mafia-room-service
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    container_name: mafia-mongo
  client:
    build:
      context: ./
      dockerfile: ${PWD}/client/docker/development/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - user-service
      - game-service
    container_name: mafia-client
    tty: true
